server:
  port: ${APP_WEBFLUX_SERVER_PORT:8081}

spring:
  application:
    name: tech-blog-webflux

openai:
  model: gpt-3.5-turbo
  api:
    url: https://api.openai.com
    key: ${OPENAI_API_KEY:ai_api-key}
